services:
  botpress:
    build:
      context: .
      dockerfile: dockerfile
    command: bash -c "./duckling & ./bp lang --offline --dim 100 --langDir /botpress & ./bp"
    container_name: botpress
    ports:
      - "3000:3000"
      - "8000:8000"
      - "3100:3100"
    environment:
      BOTPRESS_ADMIN_EMAIL: ${BOTPRESS_ADMIN_EMAIL}
      BOTPRESS_ADMIN_PASSWORD: ${BOTPRESS_ADMIN_PASSWORD}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    depends_on:
      - postgres
    restart: always
    
  postgres:
    image: postgres:16.2
    container_name: postgres_db_bp
    ports:
      - "5432:5432"
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always 

volumes:
  postgres_data:

