site_name: Chatbot Participação Social 

repo_url: https://github.com/ResidenciaTICBrisa/T2G2-Chatbot-Participacao-Social

repo_name: T2G2-Chatbot-Participacao-Social


theme:
  name: dracula
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.footer
  palette:
theme:
  name: dracula
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    
  
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Mudar para o modo escuro
      primary: blue
      accent: purple

    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Mudar para o modo claro
      primary: blue
      accent: lime
  favicon: images/rasinha_logo.jpeg
  logo: images/rasinha_logo.jpeg

  language: pt-BR
  extra_css: [stylesheets/extra.css]

nav:
  - landing page: landing_pages/landing_page.html
  - Início: index.md
  - Getting started: gettingStarded.md
  - Soluções: 
    - Estilização avançada: soluções/estilizaçãoAvançada.md
    - Migração BD: soluções/migraçãoBancoDeDados.md
  - Tecnologias: tecnologias.md
  - Arquitetura: arquitetura.md
  - Documentação:
    - Cronogramas:
      - Cronograma geral: cronogramas/Cronograma Geral.md
      - Cronograma detalhado: cronogramas/Cronograma Detalhado.md

    - Releases: 
      - releases 1: releases/release1.md
      - releases 2: releases/release2.md
    - Backlog: backlog.md
    - Guia de estilo: guiaDeEstilo.md
    - Roadmap: roadmap.md
    - Storymap: storymap.md
    - MVP:
      - MVP 1: Mínimo_Produto_Viável_(MVP)/1º MVP - Telegram.md
      - MVP 2: Mínimo_Produto_Viável_(MVP)/2º MVP - Botpress.md

    - Atas de reunião:
      - Reunião 1: atas_de_reuniões/Reunião 01.md
      - Reunião 2: atas_de_reuniões/Reunião 02.md
      - Reunião 3: atas_de_reuniões/Reunião 03.md
      - Reunião 4: atas_de_reuniões/Reunião 04.md
      - Reunião 5: atas_de_reuniões/Reunião 05.md
      - Reunião 6: atas_de_reuniões/Reunião 06.md
      - Reunião 7: atas_de_reuniões/Reunião 07.md
      - Reunião 8: atas_de_reuniões/Reunião 08.md
      - Reunião 9: atas_de_reuniões/Reunião 09.md
      - Reunião 10: atas_de_reuniões/Reunião 11.md


  - Políticas:
    - Código de conduta: Políticas/CODE_OF_CONDUCT.md
    - Contribuição: Políticas/CONTRIBUTING.md
    - Licença: Políticas/políticaDeComits.md